version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: opspilot_postgres_db
    restart: always
    environment:
      POSTGRES_USER: opspilot_admin_1          # change username if needed
      POSTGRES_PASSWORD: admin@123            # use strong password in prod
      POSTGRES_DB: opspilot_db                 # default database to create
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U opspilot_admin_1" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis:
#    image: redis:7.4-alpine                   # âœ… use latest stable tag
#    container_name: finflow-redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    command: [ "redis-server", "--requirepass", "finflow@123" ]
#    environment:
#      - REDIS_PASSWORD=finflow@123
#    volumes:
#      - redis_data:/data
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-a", "finflow@123", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.6.1
#    container_name: finflow-zookeeper
#    restart: always
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#    volumes:
#      - zookeeper_data:/var/lib/zookeeper/data
#    healthcheck:
#      test: [ "CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  kafka:
#    image: confluentinc/cp-kafka:7.6.1
#    container_name: finflow-kafka
#    restart: always
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#    volumes:
#      - kafka_data:/var/lib/kafka/data
#    healthcheck:
#      test: [ "CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1" ]
#      interval: 15s
#      timeout: 10s
#      retries: 6
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: finflow-kafka-ui
#    restart: unless-stopped
#    depends_on:
#      - kafka
#      - zookeeper
#    ports:
#      - "8085:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=FinflowCluster
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#      - KAFKA_CLUSTERS_0_READONLY=false

volumes:
  postgres_data:
    driver: local
#  redis_data:
#    driver: local
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
